### ISSUE TITLE
cannot override default prefix on UniversalTranslateLoader

### ISSUE THREAD

**Issue by olezt** [ngx-universal/translate-loader#49]
**I'm submitting a ...**
```
[X] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
```

**Current behavior**
Based on documentation of UniversalTranslateLoader, I set the prefix but it still uses the default one '/assets/i18n/'.
**Expected/desired behavior**
I would expect to use the given prefix.
**Minimal reproduction of the problem with instructions**

```
export function TranslateFactory(platformId: any, http: Http): TranslateLoader {
  const browserLoader = new TranslateHttpLoader(http);
 
  return new UniversalTranslateLoader(platformId, browserLoader, '/messages/translations_', '.json');
}
```
**Environment**
* **Angular version:** 4.3.0

* **Browser:**
- [x] Chrome (desktop)

**Comment by olezt** [comment]
@fulls1z3 Why 'wontfix' label and issue closed? Aren't we supposed to provide prefix?

**Comment by fulls1z3** [comment]
@olezt soon this library will be deprecated by leveraging the use of **http interceptors** shipped with **Angular 5**. Furthermore, not only this library, but also all libraries residing under `@ngx-universal` will be deprecated the same way (*currently there remains only `config-loader` and `translate-loader`, as `express-engine` and `state-transfer` libraries are already deprecated*).

This functionality will be a part of [ng-seed/universal](https://github.com/ng-seed/universal) project.

The issue was labeled as *wontfix* due to the reasons mentioned above, and this new approach will absolutely provide you more control on the paths, and no need to update the project every time the ngx-translate library gets updated.

Stay tuned, and I'll update this issue upon these changes on [ng-seed/universal](https://github.com/ng-seed/universal).
